version: '3'
services:
  db:
    image: postgres:12
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data 
volumes:
  db_data: